language: bash
services: docker

env:
  - VERSION=1.7.3 VARIANT=fpm-alpine
  - VERSION=1.7.3 VARIANT=fpm
  - VERSION=1.7.3 VARIANT=apache

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image="yourls:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "${VARIANT}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
