version: '3.1'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_SITE: http://localhost:8080
      YOURLS_USER: username
      YOURLS_PASS: 'password'
      YOURLS_DB_USER: postgress
      YOURLS_DB_PASS: 'postgress!'
      YOURLS_DB_HOST: pgsql
#    volumes:
#      - ~/devl/github/YOURLS:/var/www/html
#      - ~/devl/github/docker-yourls/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

  pgsql:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 'postgress!'
      POSTGRES_DB: yourls
