version: '3.1'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - 8080:80
    environment:
      YOURLS_DB_PASS: 'mysql!'
      YOURLS_SITE: http://localhost:8080
      YOURLS_USER: username
      YOURLS_PASS: 'password'
#    volumes:
#      - ~/devl/github/YOURLS-mine:/var/www/html
#      - ~/devl/github/docker-yourls-mine/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql!'
